### ISSUE TITLE
Working with multiple vaults

### ISSUE THREAD

**Issue by bartverbruggen** [xeger/awsume-1password-plugin#7]
I currently have multiple 1password vault which multiple AWS vault items per vault. 

Would it be possible to add config to enable multiple vaults. I was thinking about mentioning the vault or vault id in the config:

```
# ~/.awsume/config.yaml

colors: true
fuzzy-match: false
1password:
  "arn:aws:iam::12345:mfa/tony": "VAULT_ID_X::AWS for Tony Inc."
  "arn:aws:iam::67890:mfa/xeger": "VAULT_NAME::AWS for Xeger Enterprises"
```

**Comment by xeger** [comment]
This might already work. This plugin uses the `op` CLI tool, and if I `op item list` I see items from all of my unlocked vaults.

As long as item names are unique across vaults, things should work.

What sort of errors are you encountering?

**Comment by bartverbruggen** [comment]
The problem was indeed locally they had the same name. I managed to solve this with the item ID in stead of the item name.

My bad for not updating this issue sooner. I think this issue can be closed.
